name: MirGame
main: com.Cokes_86.MirGame.MirGame
version: 1.0
author: Cokes_86
softdepend: [Vault]

commands:
  미르게임:
     description: MirsvGame main command
  테스트:
     description: MirsvGame command